import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

//import Head from './head'
import Navbar from './components/Navbar'
import Sidebar from './components/Sidebar'


export const metadata: Metadata = {
  title: 'Sentinela_Beta',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
       
        <Sidebar/>
        {children}
       
        </body>
    </html>
  )
}
